#!/usr/bin/env bash
set -e

# Generated by Stack Sprinkles — runs every setup command in order.
# Usage: chmod +x setup.sh && ./setup.sh

git init
cd frontend && npm install && cd ..
cd backend && python -m venv venv && source venv/bin/activate && pip install -r requirements.txt && cd ..
docker compose up --build
